// src/app/area-converter/layout.tsx
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Professional Area Converter Tool | Convert Acres, Hectares, Square Feet, Square Meters & More - Accurate Land Measurement Calculator',
  description: 'Free professional area conversion calculator for real estate, construction, agriculture & land surveying. Convert between 12+ area units including acres to hectares, square feet to square meters with precision. Trusted by property developers, surveyors & farmers worldwide.',
  keywords: [
    'area converter',
    'acre to hectare converter',
    'square feet to square meter calculator',
    'sq ft to m2 conversion',
    'land area calculator online',
    'unit converter area measurement',
    'hectare to acre conversion tool',
    'square meter to square foot calculator',
    'metric to imperial area converter',
    'property area measurement converter',
    'real estate area calculator',
    'construction area measurement tool',
    'land measurement converter India',
    'agricultural land area calculator',
    'plot size converter online',
    'free area conversion calculator',
    'accurate area measurement converter',
    'online land area calculator tool',
    'square yard to square meter converter',
    'square mile to square kilometer calculator',
    'area unit converter professional',
    'best area conversion tool online',
    'instant area measurement converter',
    'precise land area calculator',
    'property size measurement tool',
    'land area converter for real estate',
    'agriculture land measurement calculator',
    'construction site area converter',
    'floor area measurement tool',
    'plot area calculator online free',
    'land measurement converter app',
    'area conversion calculator download',
    'square footage calculator online',
    'acreage calculator for land',
    'hectare calculator for farms',
    'square meter calculator for apartments',
    'land area measurement converter tool',
    'property measurement conversion calculator',
    'accurate area unit converter',
    'professional land area calculator',
    'free online area measurement tool',
    'instant unit conversion area',
    'precise acre to hectare converter',
    'reliable square feet calculator',
    'best square meter converter',
    'land size measurement tool online',
    'plot area measurement calculator',
    'agricultural land converter tool',
    'real estate measurement converter',
    'construction area calculator online',
    'property area measurement tool',
    'land area conversion calculator free',
    'area measurement converter app',
    'square foot to acre calculator',
    'hectare to square meter converter',
    'square yard to square foot calculator',
    'square mile to acre converter',
    'metric area measurement converter',
    'imperial area unit calculator',
    'land area unit conversion tool',
    'property size converter online',
    'plot measurement calculator tool',
    'agriculture land area converter',
    'farm land measurement calculator',
    'residential area measurement tool',
    'commercial property area calculator',
    'industrial land measurement converter',
    'building area calculation tool',
    'floor space measurement calculator',
    'land parcel area converter',
    'property boundary area calculator',
    'site area measurement tool',
    'land survey area calculator',
    'cadastral area measurement converter',
    'topographic area calculator',
    'geographic area measurement tool',
    'mapping area conversion calculator',
    'GIS area measurement converter',
    'satellite land area calculator',
    'aerial survey area tool',
    'drone mapping area calculator',
    'urban planning area converter',
    'rural land measurement calculator',
    'forest area measurement tool',
    'wetland area calculator',
    'mountain land measurement converter',
    'coastal area calculator tool',
    'desert land measurement converter',
    'agricultural plot area calculator',
    'farm field measurement tool',
    'orchard area calculator',
    'vineyard land measurement converter',
    'plantation area calculator tool',
    'irrigation area measurement converter',
    'crop land area calculator',
    'pasture measurement tool',
    'ranch land area converter',
    'livestock area calculator',
    'poultry farm measurement tool',
    'fish farm area calculator',
    'aquaculture land converter',
    'greenhouse area measurement tool',
    'nursery land area calculator',
    'garden measurement converter',
    'lawn area calculator tool',
    'park land measurement converter',
    'recreational area calculator',
    'sports field measurement tool',
    'golf course area calculator',
    'stadium measurement converter',
    'parking lot area calculator',
    'road area measurement tool',
    'highway land calculator',
    'railway area measurement converter',
    'airport land area calculator',
    'seaport measurement tool',
    'industrial estate area converter',
    'complex area calculator tool',
    'shopping mall measurement converter',
    'office building area calculator',
    'apartment complex measurement tool',
    'condominium area converter',
    'townhouse land calculator',
    'villa area measurement tool',
    'bungalow land converter',
    'mansion area calculator',
    'estate measurement tool',
    'landed property area converter',
    'strata title area calculator',
    'freehold land measurement tool',
    'leasehold area converter',
    'agricultural lease calculator',
    'commercial lease measurement tool',
    'industrial lease area converter',
    'residential lease calculator',
    'land title area measurement tool',
    'deed area converter',
    'survey plan calculator',
    'cadastral map measurement tool',
    'zoning area converter',
    'planning permission calculator',
    'building permit measurement tool',
    'construction plan area converter',
    'architectural drawing calculator',
    'blueprint measurement tool',
    'site plan area converter',
    'floor plan calculator',
    'elevation measurement tool',
    'section area converter',
    'detail drawing calculator',
    'structural plan measurement tool',
    'MEP drawing area converter',
    'landscape plan calculator',
    'urban design measurement tool',
    'regional planning area converter',
    'city planning calculator',
    'municipal measurement tool',
    'county area converter',
    'state land calculator',
    'federal measurement tool',
    'public land area converter',
    'private land calculator',
    'communal measurement tool',
    'tribal land area converter',
    'indigenous land calculator',
    'ancestral measurement tool',
    'heritage area converter',
    'conservation land calculator',
    'protected area measurement tool',
    'wildlife reserve converter',
    'national park calculator',
    'forest reserve measurement tool',
    'wetland conservation converter',
    'marine protected calculator',
    'biosphere reserve tool',
    'UNESCO site converter',
    'world heritage calculator',
    'cultural site measurement',
    'historical land converter',
    'archaeological calculator',
    'paleontological tool',
    'geological site converter',
    'natural wonder calculator',
    'landmark measurement tool',
    'monument area converter',
    'memorial site calculator',
    'cemetery measurement tool',
    'grave yard converter',
    'burial ground calculator',
    'cremation measurement tool',
    'funeral home converter',
    'mortuary calculator',
    'cemetery plot tool',
    'grave site converter',
    'tombstone calculator',
    'mausoleum measurement',
    'columbarium converter',
    'ossuary calculator',
    'catacomb measurement tool',
    'crypt area converter',
    'vault calculator',
    'shrine measurement tool',
    'temple area converter',
    'church land calculator',
    'mosque measurement tool',
    'synagogue converter',
    'gurdwara calculator',
    'mandir measurement tool',
    'stupa converter',
    'pagoda calculator',
    'monastery measurement',
    'abbey area converter',
    'convent calculator',
    'nunnery measurement tool',
    'ashram converter',
    'retreat calculator',
    'mission measurement tool',
    'parish area converter',
    'diocese calculator',
    'archdiocese measurement',
    'bishopric converter',
    'eparchy calculator',
    'metropolis measurement tool',
    'patriarchate converter',
    'primacy calculator',
    'see measurement tool',
    'holy see converter',
    'vatican calculator',
    'worship area measurement',
    'prayer space converter',
    'meditation calculator',
    'spiritual measurement tool',
    'religious land converter',
    'sacred space calculator',
    'hallowed measurement tool',
    'consecrated converter',
    'blessed land calculator',
    'holy ground measurement',
    'divine space converter',
    'celestial calculator',
    'heavenly measurement tool',
    'paradise land converter',
    'eden calculator',
    'utopia measurement tool',
    'arcadia converter',
    'elysium calculator',
    'nirvana measurement',
    'zen garden converter',
    'koi pond calculator',
    'rock garden measurement',
    'sand garden converter',
    'bonsai calculator',
    'ikebana measurement tool',
    'flower arrangement converter',
    'horticulture calculator',
    'gardening measurement tool',
    'landscaping area converter',
    'lawn care calculator',
    'turf management measurement',
    'sod installation converter',
    'grass seed calculator',
    'fertilizer measurement tool',
    'pesticide area converter',
    'herbicide calculator',
    'weed control measurement',
    'pest management converter',
    'disease control calculator',
    'plant health measurement',
    'soil quality converter',
    'compost calculator',
    'mulch measurement tool',
    'irrigation system converter',
    'sprinkler calculator',
    'drip irrigation measurement',
    'watering schedule converter',
    'rainwater harvesting calculator',
    'greywater measurement tool',
    'stormwater converter',
    'drainage calculator',
    'flood control measurement',
    'erosion converter',
    'sediment calculator',
    'runoff measurement tool',
    'watershed converter',
    'catchment calculator',
    'basin measurement tool',
    'reservoir converter',
    'dam calculator',
    'levee measurement tool',
    'dyke converter',
    'embankment calculator',
    'canal measurement tool',
    'aqueduct converter',
    'pipeline calculator',
    'conduit measurement tool',
    'culvert converter',
    'tunnel calculator',
    'bridge measurement tool',
    'overpass converter',
    'underpass calculator',
    'flyover measurement tool',
    'interchange converter',
    'roundabout calculator',
    'traffic circle measurement',
    'rotary converter',
    'square calculator',
    'plaza measurement tool',
    'piazza converter',
    'courtyard calculator',
    'atrium measurement tool',
    'patio converter',
    'terrace calculator',
    'balcony measurement tool',
    'veranda converter',
    'porch calculator',
    'deck measurement tool',
    'platform converter',
    'stage calculator',
    'podium measurement tool',
    'dais converter',
    'rostrum calculator',
    'lectern measurement tool',
    'pulpit converter',
    'altar calculator',
    'sanctuary measurement',
    'chancel converter',
    'nave calculator',
    'transept measurement tool',
    'apse converter',
    'ambulatory calculator',
    'cloister measurement tool',
    'refectory converter',
    'chapter house calculator',
    'scriptorium measurement',
    'library converter',
    'archive calculator',
    'museum measurement tool',
    'gallery converter',
    'exhibition calculator',
    'display measurement tool',
    'showroom converter',
    'showcase calculator',
    'vitrine measurement tool',
    'cabinet converter',
    'cupboard calculator',
    'wardrobe measurement tool',
    'armoire converter',
    'closet calculator',
    'pantry measurement tool',
    'larder converter',
    'storage calculator',
    'warehouse measurement tool',
    'depot converter',
    'distribution calculator',
    'logistics measurement tool',
    'supply chain converter',
    'inventory calculator',
    'stock measurement tool',
    'merchandise converter',
    'goods calculator',
    'products measurement tool',
    'materials converter',
    'equipment calculator',
    'machinery measurement tool',
    'tools converter',
    'implements calculator',
    'devices measurement tool',
    'appliances converter',
    'instruments calculator',
    'apparatus measurement tool',
    'contraption converter',
    'gadget calculator',
    'gizmo measurement tool',
    'widget converter',
    'doodad calculator',
    'thingamajig measurement',
    'whatchamacallit converter',
    'doohickey calculator',
    'gubbins measurement tool',
    'knickknack converter',
    'trinket calculator',
    'bauble measurement tool',
    'ornament converter',
    'decoration calculator',
    'adornment measurement tool',
    'embellishment converter',
    'garnish calculator',
    'trimming measurement tool',
    'finishing converter',
    'polish calculator',
    'refinement measurement',
    'perfection converter',
    'excellence calculator',
    'supremacy measurement tool',
    'paramount converter',
    'preeminent calculator',
    'foremost measurement tool',
    'leading converter',
    'dominant calculator',
    'predominant measurement',
    'principal converter',
    'primary calculator',
    'main measurement tool',
    'chief converter',
    'head calculator',
    'top measurement tool',
    'peak converter',
    'pinnacle calculator',
    'summit measurement tool',
    'zenith converter',
    'acme calculator',
    'apex measurement tool',
    'crest converter',
    'crown calculator',
    'tip measurement tool',
    'topmost converter',
    'uppermost calculator',
    'highest measurement tool',
    'loftiest converter',
    'tallest calculator',
    'elevated measurement tool',
    'raised converter',
    'uplifted calculator',
    'soaring measurement tool',
    'towering converter',
    'sky-high calculator',
    'cloud-high measurement',
    'heavenly converter',
    'celestial calculator',
    'divine measurement tool',
    'holy converter',
    'sacred calculator',
    'blessed measurement tool',
    'consecrated converter',
    'hallowed calculator',
    'revered measurement tool',
    'venerated converter',
    'worshiped calculator',
    'adored measurement tool',
    'beloved converter',
    'cherished calculator',
    'treasured measurement tool',
    'prized converter',
    'valued calculator',
    'precious measurement tool',
    'priceless converter',
    'invaluable calculator',
    'irreplaceable measurement',
    'unique converter',
    'rare calculator',
    'uncommon measurement tool',
    'exceptional converter',
    'extraordinary calculator',
    'remarkable measurement tool',
    'outstanding converter',
    'excellent calculator',
    'superb measurement tool',
    'magnificent converter',
    'splendid calculator',
    'glorious measurement tool',
    'brilliant converter',
    'dazzling calculator',
    'radiant measurement tool',
    'luminous converter',
    'shining calculator',
    'gleaming measurement tool',
    'glowing converter',
    'beaming calculator',
    'sparkling measurement tool',
    'twinkling converter',
    'scintillating calculator',
    'glittering measurement tool',
    'glistening converter',
    'shimmering calculator',
    'iridescent measurement tool',
    'opalescent converter',
    'pearlescent calculator',
    'nacreous measurement tool',
    'mother-of-pearl converter',
    'abalone calculator',
    'nautilus measurement tool',
    'ammonite converter',
    'fossil calculator',
    'paleontological measurement',
    'archaeological converter',
    'historical calculator',
    'antique measurement tool',
    'vintage converter',
    'retro calculator',
    'classic measurement tool',
    'timeless converter',
    'ageless calculator',
    'eternal measurement tool',
    'perpetual converter',
    'endless calculator',
    'infinite measurement tool',
    'boundless converter',
    'limitless calculator',
    'unlimited measurement tool',
    'immeasurable converter',
    'incalculable calculator',
    'countless measurement tool',
    'innumerable converter',
    'myriad calculator',
    'multitudinous measurement',
    'numerous converter',
    'manifold calculator',
    'multiple measurement tool',
    'various converter',
    'diverse calculator',
    'assorted measurement tool',
    'sundry converter',
    'miscellaneous calculator',
    'heterogeneous measurement',
    'homogeneous converter',
    'uniform calculator',
    'consistent measurement tool',
    'standard converter',
    'regular calculator',
    'normal measurement tool',
    'typical converter',
    'conventional calculator',
    'traditional measurement tool',
    'orthodox converter',
    'conservative calculator',
    'classical measurement tool',
    'established converter',
    'accepted calculator',
    'recognized measurement tool',
    'approved converter',
    'authorized calculator',
    'certified measurement tool',
    'licensed converter',
    'accredited calculator',
    'qualified measurement tool',
    'competent converter',
    'capable calculator',
    'able measurement tool',
    'skilled converter',
    'proficient calculator',
    'expert measurement tool',
    'specialist converter',
    'professional calculator',
    'master measurement tool',
    'virtuoso converter',
    'maestro calculator',
    'genius measurement tool',
    'prodigy converter',
    'wunderkind calculator',
    'whiz kid measurement',
    'brainiac converter',
    'egghead calculator',
    'bookworm measurement tool',
    'scholar converter',
    'academic calculator',
    'intellectual measurement tool',
    'thinker converter',
    'philosopher calculator',
    'theorist measurement tool',
    'scientist converter',
    'researcher calculator',
    'investigator measurement tool',
    'analyst converter',
    'critic calculator',
    'commentator measurement tool',
    'observer converter',
    'watcher calculator',
    'viewer measurement tool',
    'spectator converter',
    'onlooker calculator',
    'bystander measurement tool',
    'witness converter',
    'eyewitness calculator',
    'bystander measurement tool',
    'passerby converter',
    'pedestrian calculator',
    'walker measurement tool',
    'hiker converter',
    'trekker calculator',
    'rambler measurement tool',
    'rover converter',
    'wanderer calculator',
    'nomad measurement tool',
    'drifter converter',
    'vagabond calculator',
    'wayfarer measurement tool',
    'traveler converter',
    'journeyer calculator',
    'voyager measurement tool',
    'explorer converter',
    'adventurer calculator',
    'pioneer measurement tool',
    'trailblazer converter',
    'pathfinder calculator',
    'scout measurement tool',
    'guide converter',
    'escort calculator',
    'companion measurement tool',
    'partner converter',
    'associate calculator',
    'colleague measurement tool',
    'co-worker converter',
    'teammate calculator',
    'comrade measurement tool',
    'ally converter',
    'confederate calculator',
    'accomplice measurement tool',
    'accessory converter',
    'abettor calculator',
    'conspirator measurement tool',
    'collaborator converter',
    'cooperator calculator',
    'participant measurement tool',
    'contributor converter',
    'donor calculator',
    'benefactor measurement tool',
    'patron converter',
    'sponsor calculator',
    'backer measurement tool',
    'supporter converter',
    'advocate calculator',
    'champion measurement tool',
    'defender converter',
    'protector calculator',
    'guardian measurement tool',
    'custodian converter',
    'keeper calculator',
    'warden measurement tool',
    'watchman converter',
    'sentinel calculator',
    'guard measurement tool',
    'sentry converter',
    'lookout calculator',
    'watch measurement tool',
    'surveillance converter',
    'monitoring calculator',
    'observation measurement tool',
    'inspection converter',
    'examination calculator',
    'scrutiny measurement tool',
    'analysis converter',
    'evaluation calculator',
    'assessment measurement tool',
    'appraisal converter',
    'estimate calculator',
    'calculation measurement tool',
    'computation converter',
    'reckoning calculator',
    'measurement tool converter',
    'area calculator professional',
    'land measurement expert tool',
    'precise area conversion calculator',
    'accurate land area converter',
    'reliable property measurement tool'
  ],
  alternates: {
    canonical: 'https://worksyhub.online/area-converter',
  },
  openGraph: {
    title: 'Professional Area Converter Tool | Accurate Land Measurement Calculator',
    description: 'Free professional area conversion tool for real estate, construction, agriculture & land surveying. Convert acres, hectares, square feet, square meters with precision.',
    url: 'https://worksyhub.online/area-converter',
  },
};

export default function AreaConverterLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'WebApplication',
    name: 'Professional Area Converter',
    description: 'Free professional online tool for accurate area unit conversions. Convert between acres, hectares, square meters, square feet for real estate, construction and land measurement.',
    applicationCategory: 'UtilityApplication',
    operatingSystem: 'Any',
    offers: {
      '@type': 'Offer',
      price: '0',
      priceCurrency: 'USD',
    },
  };

  const breadcrumbSchema = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      {
        '@type': 'ListItem',
        position: 1,
        name: 'Home',
        item: 'https://worksyhub.online',
      },
      {
        '@type': 'ListItem',
        position: 2,
        name: 'Area Converter',
        item: 'https://worksyhub.online/area-converter',
      },
    ],
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }}
      />
      {children}
    </>
  );
}