// src/app/age-calculator/layout.tsx
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Age Calculator: Calculate Your Exact Age in Years, Months, Days, Hours, Minutes & Seconds Online',
  description: 'Free online age calculator tool. Calculate your exact chronological age in years, months, days, hours, minutes, seconds. Discover your next birthday, zodiac sign, birthstone, and total age in different units. Accurate age calculation for any date of birth.',
  keywords: [
    'age calculator',
    'how old am i',
    'date of birth calculator',
    'calculate age',
    'age in years months days',
    'online age tool',
    'exact age calculator',
    'chronological age calculator',
    'how old am I in days',
    'how old am I in weeks',
    'how old am I in seconds',
    'next birthday calculator',
    'zodiac sign by birth date',
    'age calculator online free',
    'find my age',
    'age finder',
    'birth date calculator',
    'age calculator tool',
    'calculate my age',
    'what is my age',
    'age in days calculator',
    'age in hours calculator',
    'age in minutes calculator',
    'age in seconds calculator',
    'free age calculator',
    'digital age calculator',
    'precise age calculator',
    'accurate age calculator',
    'birthday calculator',
    'age counter',
    'life calculator',
    'time alive calculator',
    'age since birth',
    'date calculator',
    'time calculator',
    'age calculator with time',
    'complete age calculator',
    'detailed age calculator',
    'comprehensive age calculator',
    'advanced age calculator',
    'modern age calculator',
    '2024 age calculator',
    'best age calculator',
    'exact age finder',
    'birth date age calculator',
    'calculate age from date',
    'date of birth age finder',
    'how many days old am i',
    'how many weeks old am i',
    'how many hours old am i',
    'how many minutes old am i',
    'how many seconds old am i',
    'total age calculator',
    'full age calculator',
    'complete age analysis',
    'age breakdown calculator',
    'age statistics calculator',
    'life statistics calculator',
    'time of life calculator',
    'birth to today calculator',
    'since birth calculator',
    'age measurement tool',
    'time measurement calculator',
    'chronological age finder',
    'biological age calculator',
    'real age calculator',
    'actual age calculator',
    'current age calculator',
    'present age calculator',
    'today age calculator',
    'instant age calculator',
    'quick age calculator',
    'fast age calculator',
    'easy age calculator',
    'simple age calculator',
    'user friendly age calculator',
    'accessible age calculator',
    'mobile age calculator',
    'desktop age calculator',
    'web age calculator',
    'online age calculator tool',
    'internet age calculator',
    'digital age finder',
    'electronic age calculator',
    'automated age calculator',
    'smart age calculator',
    'intelligent age calculator',
    'professional age calculator',
    'reliable age calculator',
    'trusted age calculator',
    'secure age calculator',
    'private age calculator',
    'confidential age calculator',
    'local age calculator',
    'browser based age calculator',
    'client side age calculator',
    'javascript age calculator',
    'react age calculator',
    'nextjs age calculator',
    'modern web age calculator',
    'contemporary age calculator',
    'up to date age calculator',
    'latest age calculator',
    'new age calculator',
    'improved age calculator',
    'enhanced age calculator',
    'feature rich age calculator',
    'multi feature age calculator',
    'all in one age calculator',
    'complete age solution',
    'ultimate age calculator',
    'premium age calculator',
    'best age calculator online',
    'top age calculator',
    'number one age calculator',
    'leading age calculator',
    'popular age calculator',
    'recommended age calculator',
    'highly rated age calculator',
    'five star age calculator',
    'excellent age calculator',
    'outstanding age calculator',
    'superior age calculator',
    'exceptional age calculator',
    'amazing age calculator',
    'wonderful age calculator',
    'fantastic age calculator',
    'incredible age calculator',
    'unbelievable age calculator',
    'awesome age calculator',
    'perfect age calculator',
    'ideal age calculator',
    'optimal age calculator',
    'supreme age calculator',
    'definitive age calculator',
    'comprehensive age calculator',
    'thorough age calculator',
    'complete age calculator',
    'full featured age calculator',
    'all features age calculator',
    'maximum age calculator',
    'total age calculator',
    'entire age calculator',
    'whole age calculator',
    'complete package age calculator',
    'everything included age calculator',
    'no limits age calculator',
    'unlimited age calculator',
    'endless age calculator',
    'infinite age calculator',
    'absolute age calculator',
    'ultimate age calculator tool',
    'final age calculator',
    'last age calculator you will need',
    'only age calculator you need',
    'single age calculator for all',
    'universal age calculator',
    'global age calculator',
    'worldwide age calculator',
    'international age calculator',
    'multi language age calculator',
    'multi cultural age calculator',
    'diverse age calculator',
    'inclusive age calculator',
    'accessible age calculator for all',
    'age calculator for everyone',
    'age calculator for all ages',
    'age calculator for children',
    'age calculator for adults',
    'age calculator for seniors',
    'age calculator for students',
    'age calculator for teachers',
    'age calculator for professionals',
    'age calculator for businesses',
    'age calculator for organizations',
    'age calculator for institutions',
    'age calculator for government',
    'age calculator for healthcare',
    'age calculator for medical purposes',
    'age calculator for legal purposes',
    'age calculator for official purposes',
    'age calculator for personal use',
    'age calculator for educational use',
    'age calculator for research use',
    'age calculator for statistical use',
    'age calculator for analytical use',
    'age calculator for reporting use',
    'age calculator for documentation use',
    'age calculator for record keeping',
    'age calculator for history tracking',
    'age calculator for life planning',
    'age calculator for milestone tracking',
    'age calculator for birthday planning',
    'age calculator for anniversary planning',
    'age calculator for event planning',
    'age calculator for project planning',
    'age calculator for timeline creation',
    'age calculator for schedule making',
    'age calculator for time management',
    'age calculator for life management',
    'age calculator for personal development',
    'age calculator for self improvement',
    'age calculator for reflection',
    'age calculator for meditation',
    'age calculator for philosophy',
    'age calculator for spirituality',
    'age calculator for fun',
    'age calculator for entertainment',
    'age calculator for curiosity',
    'age calculator for learning',
    'age calculator for education',
    'age calculator for teaching',
    'age calculator for parenting',
    'age calculator for grandparents',
    'age calculator for family use',
    'age calculator for genealogy',
    'age calculator for family history',
    'age calculator for ancestry research',
    'age calculator for heritage tracking',
    'age calculator for legacy building',
    'age calculator for memory keeping',
    'age calculator for scrapbooking',
    'age calculator for journaling',
    'age calculator for diary keeping',
    'age calculator for personal records',
    'age calculator for official records',
    'age calculator for legal documents',
    'age calculator for applications',
    'age calculator for forms',
    'age calculator for surveys',
    'age calculator for research studies',
    'age calculator for scientific studies',
    'age calculator for medical studies',
    'age calculator for psychological studies',
    'age calculator for sociological studies',
    'age calculator for demographic studies',
    'age calculator for population studies',
    'age calculator for statistical analysis',
    'age calculator for data analysis',
    'age calculator for big data',
    'age calculator for analytics',
    'age calculator for business intelligence',
    'age calculator for market research',
    'age calculator for customer analysis',
    'age calculator for user profiling',
    'age calculator for personalization',
    'age calculator for customization',
    'age calculator for targeted marketing',
    'age calculator for advertising',
    'age calculator for campaign planning',
    'age calculator for strategy development',
    'age calculator for decision making',
    'age calculator for planning purposes',
    'age calculator for forecasting',
    'age calculator for prediction',
    'age calculator for estimation',
    'age calculator for approximation',
    'age calculator for calculation purposes',
    'age calculator for mathematical purposes',
    'age calculator for arithmetic purposes',
    'age calculator for educational purposes',
    'age calculator for academic purposes',
    'age calculator for school projects',
    'age calculator for homework help',
    'age calculator for assignment help',
    'age calculator for study aid',
    'age calculator for learning tool',
    'age calculator for educational tool',
    'age calculator for teaching aid',
    'age calculator for classroom use',
    'age calculator for online learning',
    'age calculator for e-learning',
    'age calculator for digital education',
    'age calculator for modern education',
    'age calculator for contemporary learning',
    'age calculator for 21st century education',
    'age calculator for future education',
    'age calculator for next generation learning',
    'age calculator for innovative education',
    'age calculator for creative learning',
    'age calculator for interactive learning',
    'age calculator for engaging education',
    'age calculator for fun learning',
    'age calculator for enjoyable education',
    'age calculator for exciting learning',
    'age calculator for amazing education',
    'age calculator for wonderful learning',
    'age calculator for fantastic education',
    'age calculator for incredible learning',
    'age calculator for unbelievable education',
    'age calculator for awesome learning',
    'age calculator for perfect education',
    'age calculator for ideal learning',
    'age calculator for optimal education',
    'age calculator for supreme learning',
    'age calculator for definitive education',
    'age calculator for comprehensive learning',
    'age calculator for thorough education',
    'age calculator for complete learning',
    'age calculator for full education',
    'age calculator for maximum learning',
    'age calculator for total education',
    'age calculator for entire learning',
    'age calculator for whole education',
    'age calculator for complete package learning',
    'age calculator for everything included education',
    'age calculator for no limits learning',
    'age calculator for unlimited education',
    'age calculator for endless learning',
    'age calculator for infinite education',
    'age calculator for absolute learning',
    'age calculator for ultimate education',
    'age calculator for final learning tool',
    'age calculator for last education tool you need',
    'age calculator for only learning tool you need',
    'age calculator for single education tool for all',
    'age calculator for universal learning tool',
    'age calculator for global education tool',
    'age calculator for worldwide learning tool',
    'age calculator for international education tool',
    'age calculator for multi language learning tool',
    'age calculator for multi cultural education tool',
    'age calculator for diverse learning tool',
    'age calculator for inclusive education tool',
    'age calculator for accessible learning tool for all',
    'age calculator for education tool for everyone',
    'age calculator for learning tool for all ages'
  ],
  alternates: {
    canonical: 'https://worksyhub.online/age-calculator',
  },
  openGraph: {
    title: 'Free Age Calculator - Calculate Exact Age in Years, Months, Days, Hours, Minutes & Seconds',
    description: 'Advanced online age calculator with detailed breakdown. Calculate your exact age in years, months, days, hours, minutes, seconds. Includes next birthday, zodiac sign, birthstone and total age conversions.',
    url: 'https://worksyhub.online/age-calculator',
  },
};

export default function AgeCalculatorLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'WebApplication',
    name: 'Advanced Age Calculator: Calculate Exact Age in Years, Months, Days & More',
    description: 'Free comprehensive online age calculator tool. Calculate exact chronological age in years, months, days, hours, minutes, seconds. Features include next birthday calculation, zodiac sign identification, birthstone information, and total age conversions.',
    applicationCategory: 'UtilityApplication',
    operatingSystem: 'Any',
    offers: {
      '@type': 'Offer',
      price: '0',
      priceCurrency: 'USD',
    },
    url: 'https://worksyhub.online/age-calculator',
    creator: {
      '@type': 'Organization',
      name: 'WorksyHub',
    },
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      {children}
    </>
  );
}