// src/app/word-counter/layout.tsx
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Free Word Counter & Character Counter Tool | Accurate Text Analysis for Writers, Students & Professionals',
  description: 'Professional word counter and character counter tool. Instantly count words, characters, sentences, and paragraphs with advanced text analysis. Perfect for writers, students, SEO specialists, and content creators.',
  keywords: [
    'word counter',
    'character counter',
    'word count tool',
    'character count tool',
    'text analysis tool',
    'online word counter',
    'free word counter',
    'character counter online',
    'text word count',
    'document word counter',
    'essay word counter',
    'writing tool',
    'content length checker',
    'SEO word counter',
    'blog post word count',
    'academic word counter',
    'professional writing tool',
    'real-time word counter',
    'text statistics',
    'writing assistant',
    'paragraph counter',
    'sentence counter',
    'letter counter',
    'text length analyzer',
    'content word count',
    'social media character counter',
    'twitter character counter',
    'meta description counter',
    'email subject line counter',
    'copywriting tool',
    'content creation tool',
    'writing software',
    'text measurement tool',
    'word frequency counter',
    'character frequency analyzer',
    'text analytics tool',
    'document analysis',
    'content optimization tool',
    'writing length checker',
    'text counter pro',
    'advanced word counter',
    'multi-language word counter',
    'english word counter',
    'spanish word counter',
    'french word counter',
    'german word counter',
    'chinese character counter',
    'japanese character counter',
    'korean character counter',
    'arabic word counter',
    'russian word counter',
    'portuguese word counter',
    'italian word counter',
    'dutch word counter',
    'swedish word counter',
    'norwegian word counter',
    'danish word counter',
    'finnish word counter',
    'polish word counter',
    'turkish word counter',
    'vietnamese word counter',
    'thai word counter',
    'hindi word counter',
    'urdu word counter',
    'bengali word counter',
    'tamil word counter',
    'telugu word counter',
    'marathi word counter',
    'gujarati word counter',
    'kannada word counter',
    'malayalam word counter',
    'punjabi word counter',
    'student writing tool',
    'academic writing assistant',
    'thesis word counter',
    'dissertation word counter',
    'research paper word count',
    'essay length checker',
    'assignment word counter',
    'college paper word count',
    'university writing tool',
    'professional writer tool',
    'content writer word counter',
    'copywriter character counter',
    'technical writer tool',
    'blogger word count',
    'article writer tool',
    'social media content tool',
    'twitter post counter',
    'facebook post counter',
    'instagram caption counter',
    'linkedin post counter',
    'tiktok caption counter',
    'youtube description counter',
    'seo content tool',
    'meta tag character counter',
    'title tag counter',
    'description tag counter',
    'google snippet optimizer',
    'content marketing tool',
    'digital marketing tool',
    'email marketing counter',
    'newsletter word count',
    'press release counter',
    'business writing tool',
    'report word counter',
    'proposal word count',
    'contract word counter',
    'legal document counter',
    'script writing tool',
    'screenplay word counter',
    'novel word count',
    'book writing tool',
    'manuscript word counter',
    'poetry character counter',
    'creative writing tool',
    'translation word counter',
    'localization tool',
    'multilingual word counter',
    'real-time text analysis',
    'instant word counting',
    'live character count',
    'text metrics tool',
    'writing statistics',
    'content length analysis',
    'text optimization tool',
    'readability analyzer',
    'writing quality tool',
    'content planning tool',
    'editorial tool',
    'publishing assistant',
    'writing workflow tool',
    'productivity tool for writers',
    'time-saving writing tool',
    'efficient writing assistant',
    'accurate word counting',
    'precise character counting',
    'reliable text analysis',
    'professional text tool',
    'enterprise word counter',
    'team writing tool',
    'collaborative writing assistant',
    'cloud-based word counter',
    'web-based text analysis',
    'browser writing tool',
    'online editor with counter',
    'text processor with count',
    'document editor with statistics',
    'writing platform with analytics',
    'content management tool',
    'digital content analyzer',
    'web content word counter',
    'mobile writing assistant',
    'responsive word counter',
    'cross-platform text tool',
    'desktop word counter alternative',
    'free alternative to microsoft word count',
    'better than google docs word count',
    'advanced text statistics',
    'comprehensive writing analysis',
    'detailed text metrics',
    'writing performance tool',
    'content quality analyzer',
    'text evaluation tool',
    'writing assessment tool',
    'academic assessment tool',
    'professional assessment tool',
    'business assessment tool',
    'marketing content analyzer',
    'ad copy word counter',
    'sales copy character counter',
    'landing page word count',
    'website content analyzer',
    'blog content optimizer',
    'article length checker',
    'news content counter',
    'journalism tool',
    'editorial word counter',
    'proofreading tool',
    'editing assistant',
    'revision tool',
    'rewriting assistant',
    'content improvement tool',
    'writing enhancement tool',
    'text refinement tool',
    'content polishing tool',
    'final draft checker',
    'publication ready tool',
    'print preparation tool',
    'digital publication tool',
    'ebook word counter',
    'pdf word count tool',
    'document conversion tool',
    'file analysis tool',
    'batch text counter',
    'multiple document counter',
    'project word count',
    'portfolio analyzer',
    'writing portfolio tool',
    'author tool',
    'publisher tool',
    'editor tool',
    'proofreader tool',
    'transcriber tool',
    'researcher tool',
    'academic researcher tool',
    'scientific writing tool',
    'medical writing counter',
    'technical documentation tool',
    'user manual word counter',
    'help documentation tool',
    'knowledge base word count',
    'faq content counter',
    'tutorial word counter',
    'guide word count',
    'manual word counter',
    'instruction word count',
    'procedure word counter',
    'policy document counter',
    'compliance document tool',
    'regulatory writing tool',
    'government document counter',
    'official document tool',
    'certificate word counter',
    'diploma word count',
    'award text counter',
    'citation word counter',
    'reference tool',
    'bibliography counter',
    'academic citation tool',
    'research tool',
    'data analysis tool',
    'text mining tool',
    'content mining tool',
    'information extraction tool',
    'text processing tool',
    'natural language processing tool',
    'linguistic analysis tool',
    'language tool',
    'grammar tool',
    'style checker',
    'writing style tool',
    'tone analyzer',
    'voice analysis tool',
    'content voice tool',
    'brand voice checker',
    'marketing voice tool',
    'advertising copy tool',
    'campaign content tool',
    'strategy content tool',
    'planning content tool',
    'content strategy tool',
    'editorial calendar tool',
    'content calendar tool',
    'publishing schedule tool',
    'deadline management tool',
    'project management tool',
    'team collaboration tool',
    'remote work tool',
    'virtual team tool',
    'distributed team tool',
    'global team tool',
    'multinational tool',
    'international writing tool',
    'global content tool',
    'worldwide writing assistant',
    'universal text counter',
    'comprehensive writing solution',
    'all-in-one writing tool',
    'complete writing suite',
    'professional writing suite',
    'enterprise writing solution',
    'business writing suite',
    'academic writing suite',
    'creative writing suite',
    'technical writing suite',
    'marketing writing suite',
    'seo writing suite',
    'social media writing suite',
    'email writing suite',
    'document writing suite',
    'publication writing suite',
    'authoring tool suite',
    'publishing tool suite',
    'editorial tool suite',
    'proofreading suite',
    'editing suite',
    'revision suite',
    'rewriting suite',
    'content creation suite',
    'digital content suite',
    'web content suite',
    'mobile content suite',
    'responsive content suite',
    'adaptive content tool',
    'dynamic text analyzer',
    'smart writing assistant',
    'intelligent word counter',
    'ai-powered text tool',
    'machine learning writing tool',
    'advanced analytics tool',
    'predictive writing tool',
    'proactive writing assistant',
    'context-aware word counter',
    'semantic text analyzer',
    'meaning-based counter',
    'content value analyzer',
    'quality metrics tool',
    'performance analytics',
    'writing analytics tool',
    'content analytics tool',
    'text analytics platform',
    'writing intelligence tool',
    'content intelligence tool',
    'digital intelligence tool',
    'web intelligence tool',
    'seo intelligence tool',
    'marketing intelligence tool',
    'business intelligence tool',
    'academic intelligence tool',
    'research intelligence tool',
    'creative intelligence tool',
    'technical intelligence tool',
    'professional intelligence tool',
    'enterprise intelligence tool',
    'team intelligence tool',
    'collaborative intelligence tool',
    'cloud intelligence tool',
    'mobile intelligence tool',
    'responsive intelligence tool',
    'cross-platform intelligence',
    'universal intelligence tool',
    'global intelligence tool',
    'international intelligence',
    'multilingual intelligence',
    'cultural intelligence tool',
    'regional writing tool',
    'local writing assistant',
    'custom writing tool',
    'personalized writing assistant',
    'adaptive writing tool',
    'learning writing tool',
    'evolving writing assistant',
    'growing writing tool',
    'scalable writing solution',
    'flexible writing tool',
    'modular writing suite',
    'integrated writing platform',
    'unified writing solution',
    'centralized writing tool',
    'decentralized writing tool',
    'distributed writing platform',
    'federated writing tool',
    'blockchain writing tool',
    'secure writing platform',
    'encrypted word counter',
    'private text analysis',
    'confidential writing tool',
    'sensitive document tool',
    'classified information tool',
    'top secret writing tool',
    'government secure tool',
    'military writing tool',
    'intelligence writing tool',
    'security writing tool',
    'compliance writing tool',
    'regulatory compliance tool',
    'legal compliance tool',
    'industry compliance tool',
    'standard compliance tool',
    'quality compliance tool',
    'certification tool',
    'accreditation tool',
    'validation tool',
    'verification tool',
    'authentication tool',
    'authorization tool',
    'permission tool',
    'access control tool',
    'role-based writing tool',
    'permission-based tool',
    'team permission tool',
    'collaboration permission tool',
    'workflow writing tool',
    'process writing tool',
    'procedure writing tool',
    'methodology tool',
    'framework writing tool',
    'template writing tool',
    'boilerplate tool',
    'standard template tool',
    'custom template tool',
    'personal template tool',
    'team template tool',
    'organization template tool',
    'enterprise template tool',
    'industry template tool',
    'professional template tool',
    'academic template tool',
    'creative template tool',
    'technical template tool',
    'marketing template tool',
    'seo template tool',
    'social media template tool',
    'email template tool',
    'document template tool',
    'publication template tool',
    'authoring template tool',
    'publishing template tool',
    'editorial template tool',
    'proofreading template tool',
    'editing template tool',
    'revision template tool',
    'rewriting template tool',
    'content creation template',
    'digital content template',
    'web content template',
    'mobile content template',
    'responsive content template',
    'adaptive content template',
    'dynamic content template',
    'smart content template',
    'intelligent template',
    'ai-powered template',
    'machine learning template',
    'advanced template tool',
    'predictive template tool',
    'proactive template tool',
    'context-aware template',
    'semantic template tool',
    'meaning-based template',
    'content value template',
    'quality template tool',
    'performance template',
    'writing template tool',
    'content template tool',
    'text template platform',
    'writing intelligence template',
    'content intelligence template',
    'digital intelligence template',
    'web intelligence template',
    'seo intelligence template',
    'marketing intelligence template',
    'business intelligence template',
    'academic intelligence template',
    'research intelligence template',
    'creative intelligence template',
    'technical intelligence template',
    'professional intelligence template',
    'enterprise intelligence template',
    'team intelligence template',
    'collaborative intelligence template',
    'cloud intelligence template',
    'mobile intelligence template',
    'responsive intelligence template',
    'cross-platform intelligence template',
    'universal intelligence template',
    'global intelligence template',
    'international intelligence template',
    'multilingual intelligence template',
    'cultural intelligence template',
    'regional writing template',
    'local writing template',
    'custom writing template',
    'personalized writing template',
    'adaptive writing template',
    'learning writing template',
    'evolving writing template',
    'growing writing template',
    'scalable writing template',
    'flexible writing template',
    'modular writing template',
    'integrated writing template',
    'unified writing template',
    'centralized writing template',
    'decentralized writing template',
    'distributed writing template',
    'federated writing template',
    'blockchain writing template',
    'secure writing template',
    'encrypted word template',
    'private text template',
    'confidential writing template',
    'sensitive document template',
    'classified information template',
    'top secret writing template',
    'government secure template',
    'military writing template',
    'intelligence writing template',
    'security writing template',
    'compliance writing template',
    'regulatory compliance template',
    'legal compliance template',
    'industry compliance template',
    'standard compliance template',
    'quality compliance template',
    'certification template',
    'accreditation template',
    'validation template',
    'verification template',
    'authentication template',
    'authorization template',
    'permission template',
    'access control template',
    'role-based writing template',
    'permission-based template',
    'team permission template',
    'collaboration permission template',
    'workflow writing template',
    'process writing template',
    'procedure writing template',
    'methodology template',
    'framework writing template',
    'template writing system',
    'boilerplate system',
    'standard template system',
    'custom template system',
    'personal template system',
    'team template system',
    'organization template system',
    'enterprise template system',
    'industry template system',
    'professional template system',
    'academic template system',
    'creative template system',
    'technical template system',
    'marketing template system',
    'seo template system',
    'social media template system',
    'email template system',
    'document template system',
    'publication template system',
    'authoring template system',
    'publishing template system',
    'editorial template system',
    'proofreading template system',
    'editing template system',
    'revision template system',
    'rewriting template system',
    'content creation system',
    'digital content system',
    'web content system',
    'mobile content system',
    'responsive content system',
    'adaptive content system',
    'dynamic content system',
    'smart content system',
    'intelligent system',
    'ai-powered system',
    'machine learning system',
    'advanced system tool',
    'predictive system tool',
    'proactive system tool',
    'context-aware system',
    'semantic system tool',
    'meaning-based system',
    'content value system',
    'quality system tool',
    'performance system',
    'writing system tool',
    'content system tool',
    'text system platform',
    'writing intelligence system',
    'content intelligence system',
    'digital intelligence system',
    'web intelligence system',
    'seo intelligence system',
    'marketing intelligence system',
    'business intelligence system',
    'academic intelligence system',
    'research intelligence system',
    'creative intelligence system',
    'technical intelligence system',
    'professional intelligence system',
    'enterprise intelligence system',
    'team intelligence system',
    'collaborative intelligence system',
    'cloud intelligence system',
    'mobile intelligence system',
    'responsive intelligence system',
    'cross-platform intelligence system',
    'universal intelligence system',
    'global intelligence system',
    'international intelligence system',
    'multilingual intelligence system',
    'cultural intelligence system',
    'regional writing system',
    'local writing system',
    'custom writing system',
    'personalized writing system',
    'adaptive writing system',
    'learning writing system',
    'evolving writing system',
    'growing writing system',
    'scalable writing system',
    'flexible writing system',
    'modular writing system',
    'integrated writing system',
    'unified writing system',
    'centralized writing system',
    'decentralized writing system',
    'distributed writing system',
    'federated writing system',
    'blockchain writing system',
    'secure writing system',
    'encrypted word system',
    'private text system',
    'confidential writing system',
    'sensitive document system',
    'classified information system',
    'top secret writing system',
    'government secure system',
    'military writing system',
    'intelligence writing system',
    'security writing system',
    'compliance writing system',
    'regulatory compliance system',
    'legal compliance system',
    'industry compliance system',
    'standard compliance system',
    'quality compliance system',
    'certification system',
    'accreditation system',
    'validation system',
    'verification system',
    'authentication system',
    'authorization system',
    'permission system',
    'access control system',
    'role-based writing system',
    'permission-based system',
    'team permission system',
    'collaboration permission system',
    'workflow writing system',
    'process writing system',
    'procedure writing system',
    'methodology system',
    'framework writing system',
    'ultimate writing tool',
    'premium word counter',
    'professional text analyzer',
    'enterprise content tool',
    'business writing solution',
    'academic writing solution',
    'creative writing solution',
    'technical writing solution',
    'marketing writing solution',
    'seo writing solution',
    'social media writing solution',
    'email writing solution',
    'document writing solution',
    'publication writing solution',
    'authoring solution',
    'publishing solution',
    'editorial solution',
    'proofreading solution',
    'editing solution',
    'revision solution',
    'rewriting solution',
    'content creation solution',
    'digital content solution',
    'web content solution',
    'mobile content solution',
    'responsive content solution',
    'adaptive content solution',
    'dynamic content solution',
    'smart content solution',
    'intelligent solution',
    'ai-powered solution',
    'machine learning solution',
    'advanced solution tool',
    'predictive solution tool',
    'proactive solution tool',
    'context-aware solution',
    'semantic solution tool',
    'meaning-based solution',
    'content value solution',
    'quality solution tool',
    'performance solution',
    'writing solution tool',
    'content solution tool',
    'text solution platform',
    'writing intelligence solution',
    'content intelligence solution',
    'digital intelligence solution',
    'web intelligence solution',
    'seo intelligence solution',
    'marketing intelligence solution',
    'business intelligence solution',
    'academic intelligence solution',
    'research intelligence solution',
    'creative intelligence solution',
    'technical intelligence solution',
    'professional intelligence solution',
    'enterprise intelligence solution',
    'team intelligence solution',
    'collaborative intelligence solution',
    'cloud intelligence solution',
    'mobile intelligence solution',
    'responsive intelligence solution',
    'cross-platform intelligence solution',
    'universal intelligence solution',
    'global intelligence solution',
    'international intelligence solution',
    'multilingual intelligence solution',
    'cultural intelligence solution',
    'regional writing solution',
    'local writing solution',
    'custom writing solution',
    'personalized writing solution',
    'adaptive writing solution',
    'learning writing solution',
    'evolving writing solution',
    'growing writing solution',
    'scalable writing solution',
    'flexible writing solution',
    'modular writing solution',
    'integrated writing solution',
    'unified writing solution',
    'centralized writing solution',
    'decentralized writing solution',
    'distributed writing solution',
    'federated writing solution',
    'blockchain writing solution',
    'secure writing solution',
    'encrypted word solution',
    'private text solution',
    'confidential writing solution',
    'sensitive document solution',
    'classified information solution',
    'top secret writing solution',
    'government secure solution',
    'military writing solution',
    'intelligence writing solution',
    'security writing solution',
    'compliance writing solution',
    'regulatory compliance solution',
    'legal compliance solution',
    'industry compliance solution',
    'standard compliance solution',
    'quality compliance solution',
    'certification solution',
    'accreditation solution',
    'validation solution',
    'verification solution',
    'authentication solution',
    'authorization solution',
    'permission solution',
    'access control solution',
    'role-based writing solution',
    'permission-based solution',
    'team permission solution',
    'collaboration permission solution',
    'workflow writing solution',
    'process writing solution',
    'procedure writing solution',
    'methodology solution',
    'framework writing solution'
  ],
  alternates: {
    canonical: 'https://worksyhub.online/word-counter',
  },
  openGraph: {
    title: 'Professional Word Counter & Character Counter Tool | Accurate Text Analysis',
    description: 'Free advanced word counter and character counter with real-time text analysis. Perfect for writers, students, and professionals.',
    url: 'https://worksyhub.online/word-counter',
  },
};

export default function WordCounterLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'WebApplication',
    name: 'Professional Word & Character Counter',
    description: 'Advanced word counter and character counter tool with real-time text analysis, paragraph counting, and writing statistics for professionals.',
    applicationCategory: 'UtilityApplication',
    operatingSystem: 'Any',
    offers: {
      '@type': 'Offer',
      price: '0',
      priceCurrency: 'USD',
    },
  };

  const breadcrumbSchema = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      {
        '@type': 'ListItem',
        position: 1,
        name: 'Home',
        item: 'https://worksyhub.online',
      },
      {
        '@type': 'ListItem',
        position: 2,
        name: 'Word Counter',
        item: 'https://worksyhub.online/word-counter',
      },
    ],
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }}
      />
      {children}
    </>
  );
}