// src/app/stopwatch/layout.tsx
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Free Online Stopwatch with Lap Timer | Precision Time Tracking Tool for Sports, Workouts & Productivity',
  description: 'Accurate digital stopwatch with lap counter, keyboard shortcuts, and split timing. Perfect for sports timing, fitness training, cooking, study sessions, and productivity tracking. No download required.',
  keywords: [
    'stopwatch',
    'online stopwatch',
    'lap timer',
    'digital stopwatch',
    'time tracking',
    'sports timer',
    'fitness stopwatch',
    'workout timer',
    'study timer',
    'cooking timer',
    'precision timer',
    'free stopwatch',
    'web stopwatch',
    'browser stopwatch',
    'accuracy stopwatch',
    'millisecond timer',
    'interval timer',
    'split timer',
    'training timer',
    'athletic timing',
    'sports timing',
    'running timer',
    'swimming timer',
    'cycling timer',
    'exercise timer',
    'gym stopwatch',
    'Pomodoro timer',
    'productivity timer',
    'kitchen timer',
    'baking timer',
    'scientific timer',
    'lab timer',
    'classroom timer',
    'coaching timer',
    'basketball timer',
    'soccer timer',
    'football timer',
    'track timer',
    'marathon timer',
    'sprint timer',
    'interval training',
    'HIIT timer',
    'circuit training',
    'weightlifting timer',
    'yoga timer',
    'meditation timer',
    'presentation timer',
    'speech timer',
    'game timer',
    'competition timer',
    'race timer',
    'timing device',
    'time measurement',
    'chronometer',
    'stopwatch online free',
    'stopwatch with laps',
    'stopwatch web app',
    'stopwatch tool',
    'professional stopwatch',
    'athletic stopwatch',
    'coach stopwatch',
    'team sports timer',
    'individual sports timer',
    'fitness tracking',
    'workout tracking',
    'exercise tracking',
    'performance timing',
    'personal best timer',
    'lap counter',
    'split time',
    'time intervals',
    'multiple laps',
    'lap recording',
    'time splits',
    'pace calculator',
    'speed timer',
    'reaction timer',
    'precision timing',
    'accurate stopwatch',
    'digital timer',
    'electronic stopwatch',
    'web-based stopwatch',
    'mobile stopwatch',
    'desktop stopwatch',
    'cross-platform stopwatch',
    'keyboard stopwatch',
    'shortcut stopwatch',
    'spacebar timer',
    'one-click timer',
    'easy stopwatch',
    'simple timer',
    'user-friendly stopwatch',
    'no registration stopwatch',
    'instant stopwatch',
    'quick timer',
    'reliable stopwatch',
    'stable timer',
    'smooth stopwatch',
    'responsive timer',
    'modern stopwatch',
    'clean stopwatch',
    'minimalist timer',
    'professional timer',
    'advanced stopwatch',
    'feature-rich timer',
    'multi-purpose stopwatch',
    'versatile timer',
    'all-in-one stopwatch',
    'comprehensive timer',
    'best online stopwatch',
    'top stopwatch',
    'recommended timer',
    'popular stopwatch',
    'trusted timer',
    'proven stopwatch',
    'tested timer',
    'calibrated stopwatch',
    'synchronized timer',
    'browser-based stopwatch',
    'HTML5 stopwatch',
    'JavaScript timer',
    'modern web timer',
    'contemporary stopwatch',
    'innovative timer',
    'smart stopwatch',
    'intelligent timer',
    'customizable stopwatch',
    'flexible timer',
    'export laps',
    'save times',
    'record results',
    'track progress',
    'monitor performance',
    'analyze timing',
    'compare laps',
    'improve timing',
    'enhance performance',
    'optimize training',
  ],
  alternates: {
    canonical: 'https://worksyhub.online/stopwatch',
  },
  openGraph: {
    title: 'Free Online Stopwatch with Lap Timer | Precision Sports & Fitness Timing Tool',
    description: 'Professional-grade digital stopwatch with lap counter, keyboard shortcuts, and millisecond accuracy for sports, workouts, and productivity tracking.',
    url: 'https://worksyhub.online/stopwatch',
  },
};

export default function StopwatchLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'WebApplication',
    name: 'Online Stopwatch with Lap Timer',
    description: 'A free, precise digital stopwatch with lap timing functionality, keyboard shortcuts, and professional timing features for sports, fitness, and productivity.',
    applicationCategory: 'UtilityApplication',
    operatingSystem: 'Any',
    offers: {
      '@type': 'Offer',
      price: '0',
      priceCurrency: 'USD',
    },
    featureList: [
      'Lap/Split Timing',
      'Keyboard Shortcuts',
      'Millisecond Accuracy',
      'Lap History Tracking',
      'Spacebar Control',
      'Professional Timing',
      'Sports Ready',
      'Fitness Optimized'
    ]
  };

  const breadcrumbSchema = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      {
        '@type': 'ListItem',
        position: 1,
        name: 'Home',
        item: 'https://worksyhub.online',
      },
      {
        '@type': 'ListItem',
        position: 2,
        name: 'Stopwatch',
        item: 'https://worksyhub.online/stopwatch',
      },
    ],
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }}
      />
      {children}
    </>
  );
}