// src/app/decision-wheel/layout.tsx
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Free Decision Wheel - Online Random Picker Tool | Spin to Choose Winners',
  description: 'Make random decisions easily with our free online decision wheel spinner. Add custom options, spin the wheel, and get instant results. Perfect for giveaways, prize drawings, or daily choices.',
  keywords: [
    'decision wheel',
    'spinner wheel',
    'random picker',
    'random choice generator',
    'wheel of fortune',
    'prize wheel',
    'fun tools',
    'online decision maker',
    'random selector',
    'choice wheel',
    'digital spinner',
    'fortune wheel',
    'random decision tool',
    'free spinner',
    'interactive wheel',
    'customizable wheel',
    'decision making tool',
    'random winner picker',
    'giveaway wheel',
    'prize selector',
    'online roulette wheel',
    'digital decision maker',
    'random name picker',
    'wheel spinner online',
    'virtual decision wheel',
    'chance wheel',
    'luck wheel',
    'randomizer wheel',
    'selection wheel',
    'choice picker',
    'decision helper',
    'random outcome generator',
    'digital fortune teller',
    'online chance game',
    'interactive decision tool',
    'custom wheel creator',
    'random result generator',
    'probability wheel',
    'digital spinner wheel',
    'web decision wheel',
    'free online spinner',
    'random selection tool',
    'decision wheel app',
    'online randomizer',
    'virtual spinner',
    'choice randomizer',
    'decision assistant',
    'random picker wheel',
    'digital wheel spinner',
    'online decision helper',
    'random choice maker',
    'interactive spinner',
    'custom decision wheel',
    'web spinner tool',
    'random selector wheel',
    'digital choice wheel',
    'online random selector',
    'virtual random picker',
    'decision wheel generator',
    'random result wheel',
    'interactive choice tool',
    'web-based spinner',
    'digital randomizer',
    'online decision spinner',
    'custom spinner creator',
    'random decision helper',
    'virtual choice picker',
    'web decision maker',
    'digital random selector',
    'online probability wheel',
    'interactive randomizer',
    'custom fortune wheel',
    'random outcome picker',
    'digital decision assistant',
    'web-based randomizer',
    'online selection wheel',
    'virtual decision helper',
    'custom random wheel',
    'interactive decision maker',
    'digital selection tool',
    'web spinner wheel',
    'online choice randomizer',
    'virtual random selector',
    'decision wheel application',
    'random picker tool',
    'digital interactive wheel',
    'web-based decision tool',
    'online custom spinner',
    'virtual probability wheel',
    'custom random picker',
    'interactive outcome generator',
    'digital chance wheel',
    'web random selector',
    'online decision assistant',
    'virtual spinner tool',
    'custom choice wheel',
    'interactive result picker',
    'digital fortune wheel',
    'web decision helper',
    'online random outcome tool',
    'virtual decision maker',
    'custom interactive wheel',
    'digital web spinner',
    'online chance selector',
    'virtual custom wheel',
    'random digital spinner',
    'web-based choice tool',
    'online interactive decision wheel',
    'virtual web spinner',
    'custom digital wheel',
    'interactive web randomizer',
    'digital online spinner',
    'web virtual decision tool',
    'online digital random picker',
    'virtual interactive wheel',
    'custom web-based spinner',
    'digital virtual decision maker',
    'web online random selector',
    'interactive digital choice wheel',
    'online virtual spinner tool',
    'virtual web-based decision helper',
    'custom digital randomizer',
    'web interactive probability wheel',
    'digital online fortune wheel',
    'virtual custom decision tool',
    'online web spinner application',
    'digital virtual random picker',
    'web-based interactive choice wheel',
    'virtual online decision spinner',
    'custom digital outcome generator',
    'interactive web-based fortune wheel',
    'digital virtual chance selector',
    'online interactive web spinner',
    'virtual digital decision assistant',
    'custom web random outcome tool',
    'interactive virtual probability wheel',
    'digital online custom spinner',
    'web-based virtual random selector',
    'online digital interactive decision maker',
    'virtual web custom choice wheel',
    'custom interactive digital spinner',
    'web virtual online random picker',
    'digital interactive web-based decision tool',
    'online virtual custom spinner wheel',
    'virtual digital web random selector',
    'custom online interactive decision helper',
    'interactive digital virtual spinner tool',
    'web-based online custom decision wheel',
    'digital virtual interactive random picker',
    'online web-based digital spinner application',
    'virtual interactive online decision maker tool',
    'custom digital web-based random selector wheel'
  ],
  alternates: {
    canonical: 'https://worksyhub.online/decision-wheel',
  },
  openGraph: {
    title: 'Free Decision Spinner Wheel - Random Picker Online | WorksyHub',
    description: 'A free, customizable spinner wheel to help you make random decisions or pick a winner for giveaways and contests.',
    url: 'https://worksyhub.online/decision-wheel',
  },
};

export default function DecisionWheelLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'WebApplication',
    name: 'Decision Wheel - Random Picker Tool',
    description: 'A free online spinner wheel to make random decisions, pick prizes, choose winners, or solve daily choice dilemmas with our interactive digital wheel.',
    applicationCategory: 'UtilityApplication',
    operatingSystem: 'Any',
    offers: {
      '@type': 'Offer',
      price: '0',
      priceCurrency: 'USD',
    },
  };

  const breadcrumbSchema = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      {
        '@type': 'ListItem',
        position: 1,
        name: 'Home',
        item: 'https://worksyhub.online',
      },
      {
        '@type': 'ListItem',
        position: 2,
        name: 'Decision Wheel',
        item: 'https://worksyhub.online/decision-wheel',
      },
    ],
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }}
      />
      {children}
    </>
  );
}